name: Build and Deploy Script

on:
  push:
    branches:
      - main

jobs:
  send_start_message:
    runs-on: ubuntu-latest

    name: Send a message in discord about update
    steps:
      - uses: actions/checkout@master
      - name: send custom message with args
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          args: "```Contools deploy started!\nCommit Message: ${{ github.event.head_commit.message }}```"

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Adding Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build

      - name: Deploy to gh pages
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.USERNAME }}
          npx angular-cli-ghpages --dir=dist/contools/browser --no-silent
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  send_message:
    runs-on: ubuntu-latest
    needs: [ build ]

    name: Send a success message in discord about update
    steps:
      - uses: actions/checkout@master
      - name: send custom message with args
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          args: "```Contools deployed!\nCommit Message: ${{ github.event.head_commit.message }}```\nLink: https://ConnorWilliamsGIT.github.io/contools/"

